# Generated by Django 2.2.16 on 2020-10-07 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHabitApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
