# Generated by Django 3.1.2 on 2020-10-07 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('good', models.IntegerField(blank=True, default=0, null=True)),
                ('bad', models.IntegerField(blank=True, default=0, null=True)),
                ('read', models.IntegerField(blank=True, default=0, null=True)),
                ('previous_readers', models.CharField(blank=True, default='a', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodHabitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日付')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='体重')),
                ('food_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='食品名')),
                ('food_category', models.CharField(blank=True, max_length=15, null=True, verbose_name='食品のカテゴリ')),
                ('post_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
