# Generated by Django 2.2.16 on 2020-10-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHabitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('good', models.IntegerField()),
                ('bad', models.IntegerField()),
                ('read', models.IntegerField()),
                ('readtext', models.CharField(max_length=200)),
            ],
        ),
    ]
