# Generated by Django 2.2.16 on 2020-10-05 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHabitApp', '0003_auto_20201005_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date',
            field=models.DateField(default=datetime.date(2020, 10, 5)),
        ),
    ]
