# Generated by Django 3.1.2 on 2020-10-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHabitApp', '0006_auto_20201005_1712'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodhabitmodel',
            table=None,
        ),
    ]
