# Generated by Django 2.2.16 on 2020-10-05 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHabitApp', '0006_auto_20201005_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodhabitmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='foodhabitmodel',
            name='food_category',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='foodhabitmodel',
            name='food_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='foodhabitmodel',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterModelTable(
            name='foodhabitmodel',
            table=None,
        ),
    ]
