# Generated by Django 3.1.2 on 2020-10-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHabitApp', '0007_auto_20201006_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='readtext',
            new_name='previous_readers',
        ),
    ]
