# Generated by Django 2.2.16 on 2020-10-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHabitApp', '0007_auto_20201005_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodhabitmodel',
            name='post_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
